spring:
  datasource:
    url: jdbc:mysql://139.199.192.218:3306/Web_Final
    username: root
    password: scutligu2023
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 1800000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:com/example/webfinal/mapper/XML/*.xml